### ISSUE TITLE
dome 单张，相机拍照返回后，点击图片崩溃。

### ISSUE THREAD

**Issue by xxzgithub** [cmcy/media-selector#2]

**Comment by cmcy** [comment]
能麻烦发下错误日志和手机机型吗

**Comment by xxzgithub** [comment]
手机型号： Galaxy  SM-G9300


2020-11-10 18:15:10.058 5182-5411/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 0Kb duration : 2ms lastUpdatedAfter : 60122 ms mFlush_time_threasold : 2000 mCurrentSize : 510
2020-11-10 18:15:29.403 17152-17170/? E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
2020-11-10 18:15:34.589 16378-16417/? E/Finsky: [3364] mmy.a(9): Failed to get auth token
    com.android.volley.AuthFailureError: User needs to (re)enter credentials.
        at bql.a(PG:4)
        at mmy.a(PG:8)
        at aqdp.a(PG:1)
        at anaz.a(PG:372)
        at anaz.a(PG:540)
        at aqdd.call(Unknown Source:33)
        at aull.b(Unknown Source:2)
        at aukn.run(PG:3)
        at aulm.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at aevx.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2020-11-10 18:15:36.897 1372-3449/? E/Watchdog: !@Sync 8556 [2020-11-10 18:15:36.896]
2020-11-10 18:15:50.128 16378-17733/? E/Finsky: [3441] mmy.a(9): Failed to get auth token
    com.android.volley.AuthFailureError: User needs to (re)enter credentials.
        at bql.a(PG:4)
        at mmy.a(PG:8)
        at aqdp.a(PG:1)
        at anaz.a(PG:372)
        at anaz.a(PG:540)
        at aqdd.call(Unknown Source:33)
        at aull.b(Unknown Source:2)
        at aukn.run(PG:3)
        at aulm.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at aevx.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2020-11-10 18:16:06.916 1372-3449/? E/Watchdog: !@Sync 8557 [2020-11-10 18:16:06.916]
2020-11-10 18:16:10.200 5182-5411/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 0Kb duration : 4ms lastUpdatedAfter : 60142 ms mFlush_time_threasold : 2000 mCurrentSize : 510
2020-11-10 18:16:36.935 1372-3449/? E/Watchdog: !@Sync 8558 [2020-11-10 18:16:36.935]
2020-11-10 18:16:45.227 3790-5379/? E/Backup: [GmsBackupTransport] Error sending final backup to server: 
    mdq: Http connection fails.
        at com.google.android.gms.backup.transport.BackupTransportChimeraService.a(:com.google.android.gms@203915021@20.39.15 (040408-335085812):38)
        at com.google.android.gms.backup.transport.BackupTransportChimeraService.a(:com.google.android.gms@203915021@20.39.15 (040408-335085812):87)
        at ndo.d(:com.google.android.gms@203915021@20.39.15 (040408-335085812):1)
        at ndj.call(Unknown Source:0)
        at ndo.a(:com.google.android.gms@203915021@20.39.15 (040408-335085812):4)
        at ndo.finishBackup(:com.google.android.gms@203915021@20.39.15 (040408-335085812):3)
        at android.app.backup.BackupTransport$TransportImpl.finishBackup(BackupTransport.java:627)
        at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:164)
        at android.os.Binder.transact(Binder.java:612)
        at cre.onTransact(:com.google.android.gms@203915021@20.39.15 (040408-335085812):2)
        at android.os.Binder.transact(Binder.java:612)
        at aalo.onTransact(:com.google.android.gms@203915021@20.39.15 (040408-335085812):17)
        at android.os.Binder.execTransact(Binder.java:682)
     Caused by: java.io.IOException: NetworkError
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2496)
        at android.accounts.AccountManager.-wrap0(Unknown Source:0)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2347)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
        at android.os.Binder.execTransact(Binder.java:682) 
2020-11-10 18:16:49.723 16378-16519/? E/PlayCommon: [3424] ardy.c(141): Failed to connect to server for server timestamp: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xe7d4f980: I/O error during system call, Connection reset by peer
2020-11-10 18:16:56.114 16378-16519/? E/PlayCommon: [3424] ardy.c(182): Failed to connect to server for log upload.
2020-11-10 18:16:56.115 16378-16432/? E/PlayCommon: [3377] ardy.c(141): Failed to connect to server for server timestamp: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xcfba2e60: I/O error during system call, Connection reset by peer
2020-11-10 18:16:56.669 1372-1638/? E/ViewRootImpl: sendUserActionEvent() returned.

**Comment by cmcy** [comment]
已修复，感谢反馈

**Comment by minervo** [comment]
多张图片选择，拍照之后选择后崩溃，红米Redmi Note 4 Android 6.0  小米手机的报错位置感觉也没问题不知道是怎么引起的
![WechatIMG134](https://user-images.githubusercontent.com/20939725/102766343-f21d9300-43b8-11eb-84e6-32a23f9175d1.jpeg)
